---
development:
  cloud_name: dbamzoejf
  api_key: '799183761525351'
  api_secret: lknZr-sCMuqkltQhrGU_NgXI0e0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dbamzoejf
  api_key: '799183761525351'
  api_secret: lknZr-sCMuqkltQhrGU_NgXI0e0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dbamzoejf
  api_key: '799183761525351'
  api_secret: lknZr-sCMuqkltQhrGU_NgXI0e0
  enhance_image_tag: true
  static_file_support: false
